aliases:
  # Cache Management
  - &restore-yarn-cache
    keys:
      - v0-yarn-cache
  - &save-yarn-cache
    paths:
      - ~/.cache/yarn
    key: v0-yarn-cache

  - &restore-mongodb-binaries-cache
    keys:
      - v0-mongodb-binaries
  - &save-mongodb-binaries-cache
    paths:
      - ~/.mongodb-binaries
    key: v0-mongodb-binaries

  - &restore-node-modules-cache
    keys:
      - v0-node-modules-{{ checksum "yarn.lock" }}
  - &save-node-modules-cache
    paths:
      - node_modules
    key: v0-node-modules-{{ checksum "yarn.lock" }}

  # commands
  - &yarn
    name: Install Dependencies
    command: yarn install --frozen-lockfile --production=false --non-interactive --cache-folder ~/.cache/yarn
  - &lint
    |
      yarn jest:lint
  - &test
    name: Run Tests
    command: |
      yarn jest --maxWorkers=4 --coverage --forceExit --ci
      bash <(curl -s https://codecov.io/bash)
  - &check-changes
    name: Check changes
    command: |
      .circleci/check_changes.sh
  - &build_docker_image_server
    name: Build the Docker image
    command: |
      docker build --rm=false \
        -f ./packages/server/Dockerfile \
       -t $IMAGE_NAME_SERVER .
      docker images

  # Job Filters

  # Run only for not master branches
  - &filter-only-not-master
    branches:
      ignore:
        - master
  # runs only for master, and no tags
  - &filter-only-master
    branches:
      only:
        - master
  # Run only for master and tags
  - &filter-only-master-and-tags
    tags:
      only:
      - /.*/
    branches:
      only:
      - master

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: entria/node-ci:0.1.4
    - image: circleci/redis:4.0.9

version: 2
jobs:
  # Job run for every commit in a branch different from master
  verify_pr:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-yarn-cache
      - restore-cache: *restore-node-modules-cache
      - run: *yarn
      - save_cache: *save-node-modules-cache
      - save_cache: *save-yarn-cache
      - run: *lint
      - restore_cache: *restore-mongodb-binaries-cache
      - run: *test
      - save_cache: *save-mongodb-binaries-cache
      - store_test_results:
          path: ./test-results

  install_deps:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-yarn-cache
      - restore-cache: *restore-node-modules-cache
      - run: *yarn
      - save_cache: *save-node-modules-cache
      - save_cache: *save-yarn-cache
      - persist_to_workspace:
          root: .
          paths: .

  build_server:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - setup_remote_docker
      - run: *build_docker_image_server


  check_changes:
    <<: *defaults
    steps:
      - checkout
      - run: *check-changes

workflows:
  version: 2
  full:
    jobs:
      - verify_pr:
          filters: *filter-only-not-master
      - install_deps:
          filters: *filter-only-master-and-tags
      - build_server:
          filters: *filter-only-master-and-tags
      - check_changes

